frase = str(input('Digite uma frase: '))
contagem = frase.count('A')
print('A letra "A" aparece {} vezes.'.format(contagem))
print('A letra "A" aparece pela primeira vez na posição {}.'.format(frase.find('A')))
print('A letra "A" aparece pela última vez na posição {}.'.format(frase.rfind('A')))
