n = input('Digite algo: ')
print('Qual é o tipo primitivo?', type(n))
print('Só possui espaços?', n.isspace())
print('É um número?', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É alfanumérico?', n.isalnum())
print('Está em maiúscula?', n.isupper())
print('Está em minúscula?', n.islower())
print('Está capitalizada?', n.istitle())
print(n.isascii())
